import { NextRequest, NextResponse } from "next/server";
import { Document, Packer, Paragraph, HeadingLevel, TextRun } from "docx";
import { supabaseAdmin } from "@/lib/supabase";
import { getSessionId, verifyStudentSession } from "@/lib/session";

export async function POST(req: NextRequest) {
  try {
    const sessionId = getSessionId(req);
    const { studentId, paragraphs }: { studentId: string; paragraphs: Record<string, string> } =
      await req.json();
    if (!studentId || !paragraphs) {
      return NextResponse.json({ error: "studentId and paragraphs required" }, { status: 400 });
    }
    if (!(await verifyStudentSession(studentId, sessionId))) {
      return NextResponse.json({ error: "Student not found" }, { status: 404 });
    }

    const { data: student } = await supabaseAdmin
      .from("students")
      .select("*")
      .eq("id", studentId)
      .single();
    const { data: goals } = await supabaseAdmin
      .from("iep_goals")
      .select("*")
      .eq("student_id", studentId)
      .order("position");

    if (!student || !goals) {
      return NextResponse.json({ error: "Student not found" }, { status: 404 });
    }

    const now = new Date().toISOString().slice(0, 10);
    const children: Paragraph[] = [
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun("Quarterly Progress Report — Occupational Therapy")],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Student: ", bold: true }),
          new TextRun(student.name),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Grade / School: ", bold: true }),
          new TextRun(`${student.grade} · ${student.school}`),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Eligibility: ", bold: true }),
          new TextRun(student.eligibility),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Service minutes this quarter: ", bold: true }),
          new TextRun(`${student.minutes_delivered} / ${student.minutes_prescribed}`),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Report date: ", bold: true }),
          new TextRun(now),
        ],
      }),
      new Paragraph({ children: [new TextRun("")] }),
    ];

    goals.forEach((g, i) => {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun(`Goal ${i + 1}`)],
        }),
        new Paragraph({
          children: [new TextRun({ text: g.text, italics: true })],
        }),
        new Paragraph({
          children: [
            new TextRun({ text: "Baseline: ", bold: true }),
            new TextRun(g.baseline),
          ],
        }),
        new Paragraph({
          children: [
            new TextRun({ text: "Criterion: ", bold: true }),
            new TextRun(g.criterion),
          ],
        }),
        new Paragraph({
          children: [
            new TextRun({ text: "Status: ", bold: true }),
            new TextRun(g.status),
          ],
        }),
        new Paragraph({ children: [new TextRun("")] }),
        new Paragraph({
          children: [new TextRun(paragraphs[g.id] ?? "[Paragraph not drafted]")],
        }),
        new Paragraph({ children: [new TextRun("")] }),
      );
    });

    children.push(
      new Paragraph({ children: [new TextRun("")] }),
      new Paragraph({
        children: [new TextRun("Generated by PraxisOT per IDEA §300.320(a)(3)(ii). Therapist signature required.")],
      }),
    );

    const doc = new Document({ sections: [{ children }] });
    const buf = await Packer.toBuffer(doc);
    const body = new Uint8Array(buf);

    return new NextResponse(body, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="quarterly-${student.name.replace(/\s+/g, "_")}-${now}.docx"`,
      },
    });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Unknown error" },
      { status: 500 },
    );
  }
}
